algoritmo "Conversor de data"
// Função : Converte data EX: 06052020 para dia 06 mês 05 ano 2020.
// Autor : HállanCosta
// Data : 06/05/2020
// Seção de Declarações 
var
   //date:caractere //Data
   date: vetor [0..2,0..10] de caractere
inicio
// Seção de Comandos
   date[1,1] <- "06092020"
   
   Escreval(date[1,0])
   //Escreva("Digite a data: ")
   //Leia(date)//06092020
   
   //Escreva("Data: ", date)

fimalgoritmo
