
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label label2;

	private global::Gtk.Entry entryNumero1;

	private global::Gtk.Label label3;

	private global::Gtk.Entry entryNumero2;

	private global::Gtk.Entry entryResponse;

	private global::Gtk.Button btnClean;

	private global::Gtk.Label label1;

	private global::Gtk.Label label4;

	private global::Gtk.Button btnMinus;

	private global::Gtk.Button btnMultiplication;

	private global::Gtk.Button btnSum;

	private global::Gtk.Button btnDivision;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Calculadora");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Número 1");
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w1.X = 27;
		w1.Y = 60;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entryNumero1 = new global::Gtk.Entry();
		this.entryNumero1.CanFocus = true;
		this.entryNumero1.Name = "entryNumero1";
		this.entryNumero1.IsEditable = true;
		this.entryNumero1.InvisibleChar = '•';
		this.fixed1.Add(this.entryNumero1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entryNumero1]));
		w2.X = 21;
		w2.Y = 87;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Número 2");
		this.fixed1.Add(this.label3);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
		w3.X = 23;
		w3.Y = 133;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entryNumero2 = new global::Gtk.Entry();
		this.entryNumero2.CanFocus = true;
		this.entryNumero2.Name = "entryNumero2";
		this.entryNumero2.IsEditable = true;
		this.entryNumero2.InvisibleChar = '•';
		this.fixed1.Add(this.entryNumero2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entryNumero2]));
		w4.X = 22;
		w4.Y = 160;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entryResponse = new global::Gtk.Entry();
		this.entryResponse.CanFocus = true;
		this.entryResponse.Name = "entryResponse";
		this.entryResponse.IsEditable = false;
		this.entryResponse.InvisibleChar = '•';
		this.fixed1.Add(this.entryResponse);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entryResponse]));
		w5.X = 24;
		w5.Y = 256;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnClean = new global::Gtk.Button();
		this.btnClean.CanFocus = true;
		this.btnClean.Name = "btnClean";
		this.btnClean.UseUnderline = true;
		this.btnClean.Label = global::Mono.Unix.Catalog.GetString("Limpar");
		this.fixed1.Add(this.btnClean);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnClean]));
		w6.X = 167;
		w6.Y = 15;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("RESPOSTA");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w7.X = 71;
		w7.Y = 216;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Calculadora");
		this.fixed1.Add(this.label4);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
		w8.X = 48;
		w8.Y = 19;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnMinus = new global::Gtk.Button();
		this.btnMinus.WidthRequest = 45;
		this.btnMinus.CanFocus = true;
		this.btnMinus.Name = "btnMinus";
		this.btnMinus.UseUnderline = true;
		this.btnMinus.Label = global::Mono.Unix.Catalog.GetString("-");
		this.fixed1.Add(this.btnMinus);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnMinus]));
		w9.X = 100;
		w9.Y = 357;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnMultiplication = new global::Gtk.Button();
		global::Gtk.Tooltips w10 = new Gtk.Tooltips();
		w10.SetTip(this.btnMultiplication, "kk", "kk");
		this.btnMultiplication.WidthRequest = 45;
		this.btnMultiplication.CanFocus = true;
		this.btnMultiplication.Name = "btnMultiplication";
		this.btnMultiplication.FocusOnClick = false;
		this.btnMultiplication.Label = global::Mono.Unix.Catalog.GetString("X");
		this.fixed1.Add(this.btnMultiplication);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnMultiplication]));
		w11.X = 41;
		w11.Y = 314;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnSum = new global::Gtk.Button();
		this.btnSum.WidthRequest = 45;
		this.btnSum.CanFocus = true;
		this.btnSum.Name = "btnSum";
		this.btnSum.UseUnderline = true;
		this.btnSum.BorderWidth = ((uint)(3));
		this.btnSum.Label = global::Mono.Unix.Catalog.GetString("+");
		this.fixed1.Add(this.btnSum);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnSum]));
		w12.X = 39;
		w12.Y = 355;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnDivision = new global::Gtk.Button();
		this.btnDivision.WidthRequest = 45;
		this.btnDivision.CanFocus = true;
		this.btnDivision.Name = "btnDivision";
		this.btnDivision.UseUnderline = true;
		this.btnDivision.Label = global::Mono.Unix.Catalog.GetString("/");
		this.fixed1.Add(this.btnDivision);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnDivision]));
		w13.X = 102;
		w13.Y = 315;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 241;
		this.DefaultHeight = 408;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnClean.Clicked += new global::System.EventHandler(this.btnClean_Click);
		this.btnMinus.Clicked += new global::System.EventHandler(this.btnMinus_Click);
		this.btnMultiplication.Clicked += new global::System.EventHandler(this.btnMultiplication_Click);
		this.btnSum.Clicked += new global::System.EventHandler(this.btnSoma_Click);
		this.btnDivision.Clicked += new global::System.EventHandler(this.btnDivision_Click);
	}
}
