
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label3;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button btnClear;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Label label7;

	private global::Gtk.Entry entryNumber1;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Label label8;

	private global::Gtk.Entry entryNumber2;

	private global::Gtk.Button button10;

	private global::Gtk.HBox hbox12;

	private global::Gtk.Entry entryResponse;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Button btnMultiplication;

	private global::Gtk.Button btnDivision;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Button btnSum;

	private global::Gtk.Button btnMinus;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Calculadora 2.0");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 15;
		this.vbox1.BorderWidth = ((uint)(12));
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.WidthRequest = 250;
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Calculadora");
		this.label3.Justify = ((global::Gtk.Justification)(2));
		this.hbox1.Add(this.label3);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label3]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnClear = new global::Gtk.Button();
		this.btnClear.CanFocus = true;
		this.btnClear.Name = "btnClear";
		this.btnClear.UseUnderline = true;
		this.btnClear.Label = global::Mono.Unix.Catalog.GetString("Limpar");
		this.hbox4.Add(this.btnClear);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btnClear]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		this.hbox1.Add(this.hbox4);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox4]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		w4.Padding = ((uint)(10));
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Número 1");
		this.hbox9.Add(this.label7);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label7]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox2.Add(this.hbox9);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox9]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.entryNumber1 = new global::Gtk.Entry();
		this.entryNumber1.CanFocus = true;
		this.entryNumber1.Name = "entryNumber1";
		this.entryNumber1.IsEditable = true;
		this.entryNumber1.InvisibleChar = '•';
		this.vbox2.Add(this.entryNumber1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.entryNumber1]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		w7.Padding = ((uint)(5));
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Número 2");
		this.hbox10.Add(this.label8);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label8]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		this.vbox2.Add(this.hbox10);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox10]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.entryNumber2 = new global::Gtk.Entry();
		this.entryNumber2.CanFocus = true;
		this.entryNumber2.Name = "entryNumber2";
		this.entryNumber2.Text = global::Mono.Unix.Catalog.GetString("0");
		this.entryNumber2.IsEditable = true;
		this.entryNumber2.InvisibleChar = '•';
		this.vbox2.Add(this.entryNumber2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.entryNumber2]));
		w10.Position = 3;
		w10.Expand = false;
		w10.Fill = false;
		w10.Padding = ((uint)(5));
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.button10 = new global::Gtk.Button();
		this.button10.HeightRequest = 50;
		this.button10.CanFocus = true;
		this.button10.Name = "button10";
		this.button10.UseUnderline = true;
		this.button10.FocusOnClick = false;
		this.button10.Label = global::Mono.Unix.Catalog.GetString("RESPOSTA");
		this.vbox1.Add(this.button10);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.button10]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.entryResponse = new global::Gtk.Entry();
		this.entryResponse.HeightRequest = 35;
		this.entryResponse.CanFocus = true;
		this.entryResponse.Name = "entryResponse";
		this.entryResponse.IsEditable = false;
		this.entryResponse.InvisibleChar = '•';
		this.hbox12.Add(this.entryResponse);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.entryResponse]));
		w13.Position = 0;
		this.vbox1.Add(this.hbox12);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox12]));
		w14.Position = 3;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.btnMultiplication = new global::Gtk.Button();
		this.btnMultiplication.WidthRequest = 150;
		this.btnMultiplication.HeightRequest = 80;
		this.btnMultiplication.CanFocus = true;
		this.btnMultiplication.Name = "btnMultiplication";
		this.btnMultiplication.UseUnderline = true;
		this.btnMultiplication.Label = global::Mono.Unix.Catalog.GetString("X");
		this.hbox6.Add(this.btnMultiplication);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.btnMultiplication]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		w15.Padding = ((uint)(5));
		// Container child hbox6.Gtk.Box+BoxChild
		this.btnDivision = new global::Gtk.Button();
		this.btnDivision.WidthRequest = 150;
		this.btnDivision.HeightRequest = 80;
		this.btnDivision.CanFocus = true;
		this.btnDivision.Name = "btnDivision";
		this.btnDivision.UseUnderline = true;
		this.btnDivision.Label = global::Mono.Unix.Catalog.GetString("/");
		this.hbox6.Add(this.btnDivision);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.btnDivision]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		this.vbox1.Add(this.hbox6);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox6]));
		w17.Position = 4;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.btnSum = new global::Gtk.Button();
		this.btnSum.WidthRequest = 150;
		this.btnSum.HeightRequest = 80;
		this.btnSum.CanFocus = true;
		this.btnSum.Name = "btnSum";
		this.btnSum.UseUnderline = true;
		this.btnSum.Label = global::Mono.Unix.Catalog.GetString("+");
		this.hbox7.Add(this.btnSum);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.btnSum]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		w18.Padding = ((uint)(5));
		// Container child hbox7.Gtk.Box+BoxChild
		this.btnMinus = new global::Gtk.Button();
		this.btnMinus.WidthRequest = 150;
		this.btnMinus.HeightRequest = 80;
		this.btnMinus.CanFocus = true;
		this.btnMinus.Name = "btnMinus";
		this.btnMinus.UseUnderline = true;
		this.btnMinus.Label = global::Mono.Unix.Catalog.GetString("-");
		this.hbox7.Add(this.btnMinus);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.btnMinus]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox1.Add(this.hbox7);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox7]));
		w20.PackType = ((global::Gtk.PackType)(1));
		w20.Position = 5;
		w20.Expand = false;
		w20.Fill = false;
		w20.Padding = ((uint)(10));
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 352;
		this.DefaultHeight = 545;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnClear.Clicked += new global::System.EventHandler(this.btnClear_Click);
		this.btnMultiplication.Clicked += new global::System.EventHandler(this.btnMultiplication_Click);
		this.btnDivision.Clicked += new global::System.EventHandler(this.btnDivision_Click);
		this.btnSum.Clicked += new global::System.EventHandler(this.btnSum_Click);
		this.btnMinus.Clicked += new global::System.EventHandler(this.btnMinus_Click);
	}
}
