
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action OpesAction;

	private global::Gtk.Action PrimeiroPlanoAction;

	private global::Gtk.Action SegundoPlanoAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menuBar;

	private global::Gtk.Label label6;

	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label label1;

	private global::Gtk.Entry entryName;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Label label2;

	private global::Gtk.Entry entryAddress;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label label3;

	private global::Gtk.Entry entryCity;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Label label4;

	private global::Gtk.Entry entryCEP;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Label label5;

	private global::Gtk.Entry entryTelephone;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView treeViewPeople;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button buttonCancel;

	private global::Gtk.Button buttonSave;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.OpesAction = new global::Gtk.Action("OpesAction", global::Mono.Unix.Catalog.GetString("Opções"), null, null);
		this.OpesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Opções");
		w1.Add(this.OpesAction, null);
		this.PrimeiroPlanoAction = new global::Gtk.Action("PrimeiroPlanoAction", global::Mono.Unix.Catalog.GetString("Primeiro plano"), null, null);
		this.PrimeiroPlanoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Primeiro plano");
		w1.Add(this.PrimeiroPlanoAction, null);
		this.SegundoPlanoAction = new global::Gtk.Action("SegundoPlanoAction", global::Mono.Unix.Catalog.GetString("Segundo plano"), null, null);
		this.SegundoPlanoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Limpar registros");
		w1.Add(this.SegundoPlanoAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Cadastro de Pessoas");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.Resizable = false;
		this.AllowShrink = true;
		this.Gravity = ((global::Gdk.Gravity)(5));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name=\'menuBar\'><menu name=\'OpesAction\' action=\'OpesAction\'><menuitem" +
				" name=\'PrimeiroPlanoAction\' action=\'PrimeiroPlanoAction\'/><menuitem name=\'Segund" +
				"oPlanoAction\' action=\'SegundoPlanoAction\'/></menu></menubar></ui>");
		this.menuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menuBar")));
		this.menuBar.HeightRequest = 30;
		this.menuBar.Name = "menuBar";
		this.vbox1.Add(this.menuBar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menuBar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.HeightRequest = 30;
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Cadastre uma pessoa");
		this.label6.UseMarkup = true;
		this.label6.Wrap = true;
        this.vbox1.Add(this.label6);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label6]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		w3.Padding = ((uint)(10));
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.WidthRequest = 60;
		this.label1.Name = "label1";
		this.label1.Xalign = 0F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Nome");
		this.hbox3.Add(this.label1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entryName = new global::Gtk.Entry();
		this.entryName.WidthRequest = 250;
		this.entryName.CanFocus = true;
		this.entryName.Name = "entryName";
		this.entryName.IsEditable = true;
		this.entryName.InvisibleChar = '•';
		this.hbox3.Add(this.entryName);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entryName]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.WidthRequest = 60;
		this.label2.Name = "label2";
		this.label2.Xalign = 0F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Endereço");
		this.hbox4.Add(this.label2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label2]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.entryAddress = new global::Gtk.Entry();
		this.entryAddress.WidthRequest = 250;
		this.entryAddress.CanFocus = true;
		this.entryAddress.Name = "entryAddress";
		this.entryAddress.IsEditable = true;
		this.entryAddress.InvisibleChar = '•';
		this.hbox4.Add(this.entryAddress);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.entryAddress]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.vbox2.Add(this.hbox4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.WidthRequest = 60;
		this.label3.Name = "label3";
		this.label3.Xalign = 0F;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Cidade");
		this.hbox5.Add(this.label3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label3]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.entryCity = new global::Gtk.Entry();
		this.entryCity.WidthRequest = 250;
		this.entryCity.CanFocus = true;
		this.entryCity.Name = "entryCity";
		this.entryCity.IsEditable = true;
		this.entryCity.InvisibleChar = '•';
		this.hbox5.Add(this.entryCity);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entryCity]));
		w11.Position = 1;
		w11.Expand = false;
		this.vbox2.Add(this.hbox5);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox5]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.WidthRequest = 60;
		this.label4.Name = "label4";
		this.label4.Xalign = 0F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("CEP");
		this.hbox6.Add(this.label4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label4]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.entryCEP = new global::Gtk.Entry();
		this.entryCEP.WidthRequest = 250;
		this.entryCEP.CanFocus = true;
		this.entryCEP.Name = "entryCEP";
		this.entryCEP.IsEditable = true;
		this.entryCEP.InvisibleChar = '•';
		this.hbox6.Add(this.entryCEP);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.entryCEP]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox2.Add(this.hbox6);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox6]));
		w15.Position = 3;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.WidthRequest = 60;
		this.label5.Name = "label5";
		this.label5.Xalign = 0F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Telefone");
		this.hbox7.Add(this.label5);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label5]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.entryTelephone = new global::Gtk.Entry();
		this.entryTelephone.WidthRequest = 250;
		this.entryTelephone.CanFocus = true;
		this.entryTelephone.Name = "entryTelephone";
		this.entryTelephone.IsEditable = true;
		this.entryTelephone.InvisibleChar = '•';
		this.hbox7.Add(this.entryTelephone);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.entryTelephone]));
		w17.Position = 1;
		w17.Expand = false;
		this.vbox2.Add(this.hbox7);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox7]));
		w18.Position = 4;
		w18.Expand = false;
		w18.Fill = false;
		this.hbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
		w19.Position = 0;
		w19.Padding = ((uint)(10));
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeViewPeople = new global::Gtk.TreeView();
		this.treeViewPeople.WidthRequest = 210;
		this.treeViewPeople.CanFocus = true;
		this.treeViewPeople.Name = "treeViewPeople";
		this.GtkScrolledWindow.Add(this.treeViewPeople);
		this.hbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
		w21.Position = 1;
		w21.Padding = ((uint)(10));
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.HeightRequest = 50;
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.buttonCancel = new global::Gtk.Button();
		this.buttonCancel.HeightRequest = 50;
		this.buttonCancel.CanFocus = true;
		this.buttonCancel.Name = "buttonCancel";
		this.buttonCancel.UseUnderline = true;
		this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
		this.hbox2.Add(this.buttonCancel);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.buttonCancel]));
		w23.Position = 0;
		w23.Padding = ((uint)(50));
		// Container child hbox2.Gtk.Box+BoxChild
		this.buttonSave = new global::Gtk.Button();
		this.buttonSave.HeightRequest = 0;
		this.buttonSave.CanFocus = true;
		this.buttonSave.Name = "buttonSave";
		this.buttonSave.Label = global::Mono.Unix.Catalog.GetString("Salvar");
		this.hbox2.Add(this.buttonSave);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.buttonSave]));
		w24.Position = 1;
		w24.Padding = ((uint)(50));
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w25.Position = 3;
		w25.Expand = false;
		w25.Fill = false;
		w25.Padding = ((uint)(20));
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 607;
		this.DefaultHeight = 377;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.PrimeiroPlanoAction.Activated += new global::System.EventHandler(this.onTop_Activated);
		this.SegundoPlanoAction.Activated += new global::System.EventHandler(this.onDown_Activated);
		this.buttonCancel.Clicked += new global::System.EventHandler(this.buttonCancel_Click);
		this.buttonSave.Clicked += new global::System.EventHandler(this.buttonSave_Click);
	}
}
