
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Relogio");
		this.TypeHint = ((global::Gdk.WindowTypeHint)(7));
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 253;
		this.DefaultHeight = 307;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
